FROM golang

# GOLANG
WORKDIR /go/src/menu-service/

RUN go get -d -v  github.com/gorilla/mux
RUN go install -v  github.com/gorilla/mux

RUN go get -d -v  github.com/gorilla/handlers
RUN go install -v  github.com/gorilla/handlers

RUN go get -d -v  github.com/google/uuid
RUN go install -v  github.com/google/uuid

COPY . .

RUN go build .
RUN go install

ENTRYPOINT /go/bin/menu-service

EXPOSE 8080